Merge v0.3.2
filecoin-project/sentinel pull request #158
Opened 2020-10-12 22:12 UTC by placer14

2020-10-12 22:15 UTC, willscott commented on .circleci/config.yml
> +      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
comment for why we need rust? should we be pinning a specific rust version?

2020-10-12 22:24 UTC, lanzafame requested changes

2020-10-12 22:24 UTC, lanzafame commented on scripts/visor-indexer.service
> +ExecStart=/usr/local/bin/sentinel-visor run indexer
This won't work with the submodule version of visor.

2020-10-12 22:24 UTC, lanzafame commented on scripts/visor-processor.service
> +ExecStart=/usr/local/bin/sentinel-visor run processor
This won't work with the submodule version of visor.

2020-10-14 05:34 UTC, lanzafame requested changes

2020-10-14 05:34 UTC, lanzafame commented on scripts/sentinel-visor.service
> +Description=Sentinel Visor Indexer
```suggestion
Description=Sentinel Visor
```

2020-10-14 05:34 UTC, lanzafame commented on scripts/sentinel-visor.service
> +Environment=GOLOG_FILE="/var/log/sentinel/visor-indexer.log"
```suggestion
Environment=GOLOG_FILE="/var/log/sentinel/visor.log"
```

2020-10-14 05:34 UTC, lanzafame commented on scripts/sentinel-visor.service
>  Environment=GOLOG_LOG_FMT="json"
```suggestion
Environment=GOLOG_LOG_FMT="json"
Environment=GOLOG_OUTPUT="file+stderr"
```
This is so that the logs go to both the file and to `journald`

2020-10-14 05:34 UTC, lanzafame commented on grafana/provisioning/dashboards/main.json
> +          "rawSql": "with epoch as (\n    select distinct on (height) height,\n           to_timestamp(timestamp) as \"time\",\n           parent_state_root\n    from block_headers\n    where to_time
```suggestion
          "rawSql": "with epoch as (\n    select distinct on (height) height,\n           to_timestamp(timestamp) as \"time\",\n           parent_state_root\n    from block_headers\n    where to_timestamp(timestamp) > date $__timeFrom() - interval '1 day'\n       and to_timestamp(timestamp) < $__timeTo()\n    group by height, timestamp, parent_state_root, parent_weight\n    order by height desc, parent_weight desc\n),\ndata as (\nselect epoch.time,\n       ((total_raw_bytes_power::numeric - avg(total_raw_bytes_power::numeric)\n                                          over (order by epoch.time rows between 479 preceding and current row)) /\n        extract(epoch from time - (time - interval '4hr')) -\n        (lag(total_raw_bytes_power::numeric, 480) over w - avg(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 959 preceding and 480 preceding)) /\n        extract(epoch from time - (time - interval '4hr'))) /\n               greatest(((lag(total_raw_bytes_power::numeric, 480) over w - avg(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 959 preceding and 480 preceding)) /\n        extract(epoch from time - (time - interval '4hr'))), 1) * 100                                                       as \"zoom-in-4hr\",\n       ((total_raw_bytes_power::numeric - avg(total_raw_bytes_power::numeric)\n                                          over (order by epoch.time rows between 479 preceding and current row)) /\n        extract(epoch from time - (time - interval '4hr')) -\n        (lag(total_raw_bytes_power::numeric, 480) over w - avg(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 959 preceding and 480 preceding)) /\n        extract(epoch from time - (time - interval '4hr'))) /\n               greatest(((lag(total_raw_bytes_power::numeric, 480) over w - avg(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 959 preceding and 480 preceding)) /\n        extract(epoch from time - (time - interval '4hr'))), 1) * 100                                                       as \"zoom-out-4hr\"\nfrom epoch\n         join chain_powers on epoch.parent_state_root = chain_powers.state_root\n    window w as (order by epoch.time)\norder by time desc\n)\nselect * from data\n    where time > $__timeFrom()\n       and time < $__timeTo()\n       order by time desc",
```

2020-10-14 05:34 UTC, lanzafame commented on grafana/provisioning/dashboards/main.json
> +          "rawSql": "-- total network power over time\nwith epoch as (\n    select distinct on (height)\n        time_bucket('30s', to_timestamp(block_headers.timestamp)) as \"time\",\n        --$__t
```suggestion
          "rawSql": "-- total network power over time\nwith epoch as (\n    select distinct on (height)\n        time_bucket('30s', to_timestamp(block_headers.timestamp)) as \"time\",\n        --$__timeGroup(blocks.timestamp, '1h'),\n        spi.state_root\n    from block_headers\n    join sector_precommit_info spi on height = spi.precommit_epoch\n    where to_timestamp(block_headers.timestamp) > $__timeFrom()\n    AND to_timestamp(block_headers.timestamp) < $__timeTo()\n    group by block_headers.timestamp, spi.state_root, height\n    order by height, time desc\n)\nselect\n    epoch.time,\n    miner_count,\n    total_raw_bytes_power::numeric,\n    total_qa_bytes_power::numeric\nfrom chain_powers\njoin epoch on epoch.state_root = chain_powers.state_root\norder by time desc;",
```

2020-10-14 05:34 UTC, lanzafame commented on grafana/provisioning/dashboards/main.json
> +          "rawSql": "with epoch as (\n    select distinct on (height) height,\n           to_timestamp(timestamp) as \"time\",\n           parent_state_root\n    from block_headers\n    where to_time
```suggestion
          "rawSql": "with epoch as (\n    select distinct on (height) height,\n           to_timestamp(timestamp) as \"time\",\n           parent_state_root\n    from block_headers\n    where to_timestamp(timestamp) > date $__timeFrom() - interval '1 day'\n       and to_timestamp(timestamp) < $__timeTo()\n    group by height, timestamp, parent_state_root, parent_weight\n    order by height desc, parent_weight desc\n),\ndata as (\nselect epoch.time,\n        ((total_raw_bytes_power::numeric - lag(total_raw_bytes_power::numeric)\n                                          over (order by epoch.time rows between 1919 preceding and current row)) /\n        extract(epoch from time - (time - interval '8hr')) -\n        (lag(total_raw_bytes_power::numeric, 1920) over w - lag(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 3839 preceding and 1920 preceding)) /\n        extract(epoch from time - (time - interval '8hr'))) /\n               greatest(((lag(total_raw_bytes_power::numeric, 1920) over w - lag(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 3839 preceding and 1920 preceding)) /\n        extract(epoch from time - (time - interval '8hr'))), 1) * 100                                                       as \"zoom-in-8hr\",\n        ((total_raw_bytes_power::numeric - lag(total_raw_bytes_power::numeric)\n                                          over (order by epoch.time rows between 959 preceding and current row)) /\n        extract(epoch from time - (time - interval '8hr')) -\n        (lag(total_raw_bytes_power::numeric, 1920) over w - lag(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 3839 preceding and 1920 preceding)) /\n        extract(epoch from time - (time - interval '8hr'))) /\n               greatest(((lag(total_raw_bytes_power::numeric, 1920) over w - lag(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 3839 preceding and 1920 preceding)) /\n        extract(epoch from time - (time - interval '8hr'))), 1) * 100                                                       as \"zoom-out-8hr\"\nfrom epoch\n         join chain_powers on epoch.parentstateroot = chain_powers.state_root\n    window w as (order by epoch.time)\norder by time desc\n)\nselect * from data\n    where time > $__timeFrom()\n       and time < $__timeTo()\n       order by time desc",
```

2020-10-14 05:34 UTC, lanzafame commented on grafana/provisioning/dashboards/main.json
> +          "rawSql": "with epoch as (\n    select distinct on (height) height,\n           to_timestamp(timestamp) as \"time\",\n           parent_state_root\n    from block_headers\n    where to_time
```suggestion
          "rawSql": "with epoch as (\n    select distinct on (height) height,\n           to_timestamp(timestamp) as \"time\",\n           parent_state_root\n    from block_headers\n    where to_timestamp(timestamp) > date $__timeFrom() - interval '1 day'\n       and to_timestamp(timestamp) < $__timeTo()\n    group by height, timestamp, parent_state_root, parent_weight\n    order by height desc, parent_weight desc\n),\ndata as (\nselect epoch.time,\n       ((total_raw_bytes_power::numeric - lag(total_raw_bytes_power::numeric)\n                                          over (order by epoch.time rows between 239 preceding and current row)) /\n        extract(epoch from time - (time - interval '2hr')) -\n        (lag(total_raw_bytes_power::numeric, 240) over w - lag(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 479 preceding and 240 preceding)) /\n        extract(epoch from time - (time - interval '2hr')))                                                        as \"zoom-in-2hr\",\n              ((total_raw_bytes_power::numeric - lag(total_raw_bytes_power::numeric)\n                                          over (order by epoch.time rows between 239 preceding and current row)) /\n        extract(epoch from time - (time - interval '2hr')) -\n        (lag(total_raw_bytes_power::numeric, 240) over w - lag(total_raw_bytes_power::numeric)\n                                                            over (order by epoch.time rows between 479 preceding and 240 preceding)) /\n        extract(epoch from time - (time - interval '2hr')))                                                       as \"zoom-out-2hr\"\nfrom epoch\n         join chain_powers on epoch.parent_state_root = chain_powers.state_root\n    window w as (order by epoch.time)\norder by time desc\n)\nselect * from data\n    where time > $__timeFrom()\n       and time < $__timeTo()\n       order by time desc",
```

2020-10-14 05:45 UTC, lanzafame approved these changes

2020-10-14 05:54 UTC, merged